export const projects = [
  {
    title: 'BENJI — Healthcare Portal',
    company: 'Emids Technologies (Client: Hansei)',
    description: 'End-to-end healthcare solutions portal with OTP-based email validation, Figma-to-code responsive UI, and RESTful API integration.',
    tech: ['ReactJS', 'Node.js', 'Express.js', 'MongoDB', 'REST APIs'],
    color: '#78cc6d',
    link: null,
  },
  {
    title: 'EDM — End Device Manager',
    company: 'NEC Corporation (Client: 7-Eleven)',
    description: 'Device-monitoring web platform used across retail locations. Reusable ReactJS components and RESTful APIs with AWS deployment.',
    tech: ['ReactJS', 'Next.js', 'Node.js', 'MongoDB', 'PgSQL', 'AWS'],
    color: '#61dafb',
    link: null,
  },
  {
    title: 'BanQsoft Ledger',
    company: 'NEC Corporation (Client: BanQsoft)',
    description: 'Credit management ledger application with GraphQL APIs, Cypress E2E test automation, and Material UI design.',
    tech: ['ReactTS', 'GraphQL', 'Next.js', 'Cypress', 'MUI', 'AWS'],
    color: '#9c6fff',
    link: 'https://www.banqsoft.com/',
  },
  {
    title: 'PitStopUSA E-Commerce',
    company: 'Pragiti Internet Technologies',
    description: 'E-commerce storefront on VTEX Marketplace with custom Legacy Order integration, email-marketing integration, and ETL data migration.',
    tech: ['VTEX', 'ReactJS', 'Next.js', 'Node.js', 'Bootstrap'],
    color: '#ff6b35',
    link: 'https://pitstopusa.myvtex.com/',
  },
  {
    title: 'QOZO Web Application',
    company: 'SkillFlare',
    description: 'Serverless web app built with ReactTS and GraphQL on AWS. Full-stack modules with DynamoDB and third-party API integrations.',
    tech: ['ReactTS', 'GraphQL', 'Node.js', 'DynamoDB', 'AWS', 'Serverless'],
    color: '#f7e018',
    link: 'https://qozo.io/',
  },
  {
    title: 'SPOT — Sales Optimization',
    company: 'OM Associates',
    description: 'Hybrid mobile & web application for U.S. clients with PayPal payment gateway integration and GCP cloud deployment.',
    tech: ['ReactJS', 'Node.js', 'Express.js', 'MongoDB', 'GCP'],
    color: '#00b4d8',
    link: 'https://spotyourdeal.com/',
  },
];
